FROM node:20-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --production
COPY backend/src ./src
COPY backend/migrations ./migrations
COPY backend/seeds ./seeds
EXPOSE 5000
CMD ["node", "src/app.js"]
